# Generated by Django 5.2.7 on 2025-10-23 23:55

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=20, unique=True)),
                ('marque', models.CharField(max_length=50)),
                ('modele', models.CharField(max_length=50)),
                ('date_mise_service', models.DateField()),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('maintenance', 'En Maintenance')], default='actif', max_length=20)),
                ('type_propriete', models.CharField(choices=[('interne', 'Interne'), ('externe', 'Externe')], default='interne', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('ice', models.CharField(max_length=20, unique=True)),
                ('adresse', models.TextField(blank=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville', models.CharField(max_length=100)),
                ('frais_deplacement', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_employe', models.CharField(choices=[('chauffeur', 'Chauffeur'), ('salarie', 'Salarié'), ('gerant', 'Gérant')], max_length=20)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('salaire_base', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('statut', models.CharField(default='actif', max_length=20)),
                ('date_embauche', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransporteurExterne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('ice', models.CharField(max_length=20, unique=True)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adresse', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif')], default='actif', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('employe', 'Employé')], default='employe', max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('date_embauche', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(default='actif', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='gestion_user_set', related_query_name='gestion_user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='gestion_user_set', related_query_name='gestion_user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ChargeCamion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_charge', models.CharField(choices=[('mensuelle', 'Mensuelle'), ('annuelle', 'Annuelle'), ('occasionnelle', 'Occasionnelle')], max_length=20)),
                ('categorie', models.CharField(choices=[('assurance', 'Assurance'), ('vignette', 'Vignette'), ('visite_technique', 'Visite Technique'), ('tachygraphe', 'Tachygraphe'), ('extincteurs', 'Extincteurs'), ('gazoil', 'Gazoil'), ('jawaz_autoroute', 'Jawaz Autoroute'), ('reparation', 'Réparation'), ('entretien', 'Entretien'), ('vidange', 'Vidange'), ('nettoyage', 'Nettoyage'), ('pneumatiques', 'Pneumatiques'), ('autre', 'Autre')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('litres', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('kilometrage', models.IntegerField(blank=True, null=True)),
                ('prix_litre', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('date_charge', models.DateField()),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(blank=True, choices=[('active', 'Active'), ('expiree', 'Expirée'), ('renouvellee', 'Renouvelée')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='gestion.camion')),
            ],
            options={
                'ordering': ['-date_charge', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(editable=False, max_length=50, unique=True)),
                ('entreprise', models.CharField(choices=[('ars_distribution', 'ARS Distribution'), ('arn_logistique', 'ARN Logistique')], max_length=20)),
                ('date_facture', models.DateField()),
                ('date_echeance', models.DateField()),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('envoyee', 'Envoyée'), ('payee', 'Payée'), ('annulee', 'Annulée')], default='brouillon', max_length=20)),
                ('conditions_paiement', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('total_ht', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_tva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.client')),
            ],
        ),
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantite', models.IntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tva', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_tva', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('montant_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ordre', models.IntegerField(default=0)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='gestion.facture')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('n_conteneurs', models.IntegerField(default=1)),
                ('numeros_conteneurs', models.CharField(blank=True, max_length=500)),
                ('prix_trajet', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frais_deplacement', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('type_trajet', models.CharField(choices=[('facture', 'Facturé'), ('non_facture', 'Non Facturé')], default='facture', max_length=20)),
                ('type_service', models.CharField(choices=[('ars_distribution', 'ARS Distribution'), ('arn_logistique', 'ARN Logistique'), ('sous_traitance', 'Sous-traitance')], default='ars_distribution', max_length=20)),
                ('type_sous_traitance', models.CharField(choices=[('je_donne', 'Je donne à un transporteur'), ('je_recois', "Je reçois d'un transporteur"), ('interne', 'Trajet interne')], default='interne', max_length=20)),
                ('prix_sous_traitance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('statut_paiement_sous_traitance', models.CharField(choices=[('paye', 'Payé'), ('non_paye', 'Non Payé'), ('partiel', 'Partiel')], default='non_paye', max_length=20)),
                ('frais_supplementaires', models.CharField(blank=True, default='{}', max_length=1000)),
                ('total_frais_supplementaires', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('statut_paiement_frais', models.CharField(choices=[('paye', 'Payé'), ('non_paye', 'Non Payé'), ('partiel', 'Partiel')], default='non_paye', max_length=20)),
                ('remarques', models.TextField(blank=True)),
                ('camion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.camion')),
                ('chauffeur', models.ForeignKey(blank=True, limit_choices_to={'type_employe': 'chauffeur'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.employe')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.client')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.destination')),
                ('transporteur_externe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.transporteurexterne')),
            ],
        ),
        migrations.CreateModel(
            name='PaiementSousTraitance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('date_echeance', models.DateField()),
                ('statut', models.CharField(choices=[('paye', 'Payé'), ('en_attente', 'En attente'), ('annule', 'Annulé')], default='en_attente', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('remarques', models.TextField(blank=True)),
                ('trajet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.trajet')),
                ('transporteur_externe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.transporteurexterne')),
            ],
        ),
        migrations.AddField(
            model_name='camion',
            name='transporteur_externe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.transporteurexterne'),
        ),
    ]
