# Generated by Django 5.2.7 on 2025-10-31 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('bloque', 'Bloqué')], default='actif', max_length=20),
        ),
        migrations.CreateModel(
            name='DeclarationTVA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entreprise', models.CharField(choices=[('arn_logistique', 'ARN Logistique'), ('ars_distribution', 'ARS Distribution')], max_length=20)),
                ('mois', models.IntegerField()),
                ('annee', models.IntegerField()),
                ('tva_collectee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tva_deductible', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tva_net_a_payer', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_credits_ht', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_debits_ht', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_credits_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_debits_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('calculee', 'Calculée'), ('declaree', 'Déclarée'), ('payee', 'Payée')], default='brouillon', max_length=20)),
                ('date_declaration', models.DateField(blank=True, null=True)),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('reference_dgi', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-annee', '-mois'],
                'unique_together': {('entreprise', 'mois', 'annee')},
            },
        ),
        migrations.CreateModel(
            name='OperationTVA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entreprise', models.CharField(choices=[('arn_logistique', 'ARN Logistique'), ('ars_distribution', 'ARS Distribution')], max_length=20)),
                ('type_operation', models.CharField(choices=[('debit', 'Débit'), ('credit', 'Crédit')], max_length=10)),
                ('date_operation', models.DateField()),
                ('date_valeur', models.DateField()),
                ('libelle', models.CharField(max_length=255)),
                ('montant_ht', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('taux_tva', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('montant_tva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_ttc', models.DecimalField(decimal_places=2, max_digits=12)),
                ('categorie', models.CharField(choices=[('vente_client', 'Vente Client'), ('achat_fournisseur', 'Achat Fournisseur'), ('carburant', 'Carburant'), ('entretien', 'Entretien Véhicule'), ('salaires', 'Salaires et Charges Sociales'), ('loyer', 'Loyer et Charges Locatives'), ('assurance', 'Assurances'), ('peage', 'Péages Autoroute'), ('divers', 'Divers'), ('impot_taxe', 'Impôts et Taxes'), ('honoraires', 'Honoraires'), ('telecom', 'Télécommunications'), ('fournitures', 'Fournitures Bureau')], max_length=50)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('beneficiaire', models.CharField(blank=True, max_length=200)),
                ('statut_tva', models.CharField(choices=[('deductible', 'TVA Déductible'), ('collectee', 'TVA Collectée'), ('neutre', 'Neutre (Sans TVA)')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Opération TVA',
                'verbose_name_plural': 'Opérations TVA',
                'ordering': ['-date_operation', '-date_valeur'],
            },
        ),
    ]
