# Generated by Django 5.2.7 on 2025-11-11 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_user_statut_declarationtva_operationtva'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoldeTransporteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_je_donne', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_je_recois', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('solde_net_calcule', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reste_a_payer', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('statut_solde', models.CharField(choices=[('non_paye', 'Non Payé'), ('partiel', 'Partiellement Payé'), ('paye', 'Entièrement Payé')], default='non_paye', max_length=20)),
                ('date_dernier_reglement', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('transporteur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solde', to='gestion.transporteurexterne')),
            ],
            options={
                'verbose_name': 'Solde Transporteur',
                'verbose_name_plural': 'Soldes Transporteurs',
            },
        ),
    ]
