# Generated by Django 5.2.7 on 2025-11-11 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_soldetransporteur'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SoldeTransporteur',
        ),
    ]
