# Generated by Django 5.2.7 on 2025-11-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_delete_soldetransporteur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationtva',
            name='categorie',
            field=models.CharField(choices=[('vente_client', 'Vente Client'), ('achat_fournisseur', 'Achat Fournisseur'), ('carburant', 'Carburant'), ('entretien_vehicule', 'Entretien Véhicule'), ('reparation_vehicule', 'Réparation Véhicule'), ('assurance_vehicule', 'Assurance Véhicule'), ('vignette_vehicule', 'Vignette Véhicule'), ('controle_technique', 'Contrôle Technique'), ('salaires', 'Salaires et Charges Sociales'), ('loyer_bureau', 'Loyer Bureau'), ('charges_locatives', 'Charges Locatives'), ('electricite_eau', 'Électricité et Eau'), ('telecom_internet', 'Télécommunications et Internet'), ('fournitures_bureau', 'Fournitures Bureau'), ('materiel_informatique', 'Matériel Informatique'), ('frais_bancaires', 'Frais Bancaires'), ('honoraires_comptable', 'Honoraires Comptable'), ('honoraires_avocat', 'Honoraires Avocat'), ('publicite_marketing', 'Publicité et Marketing'), ('voyage_deplacement', 'Voyage et Déplacement'), ('formation', 'Formation'), ('peage_autoroute', 'Péage Autoroute'), ('stationnement', 'Stationnement'), ('impot_taxe', 'Impôts et Taxes'), ('taxe_professionnelle', 'Taxe Professionnelle'), ('autres_charges', 'Autres Charges'), ('divers', 'Divers')], max_length=50),
        ),
    ]
