# Generated by Django 5.2.7 on 2025-11-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_alter_operationtva_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('employe', 'Employé'), ('facturation', 'Agent Facturation')], default='employe', max_length=20),
        ),
    ]
