# Generated by Django 5.2.7 on 2025-11-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='montant_tva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='facture',
            name='total_ht',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='facture',
            name='total_ttc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='lignefacture',
            name='montant_ht',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='lignefacture',
            name='montant_ttc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='lignefacture',
            name='montant_tva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='lignefacture',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
